application: natacalc
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /natacalc\.css
  static_files: natacalc.css
  upload: natacalc\.css

- url: /
  static_files: index.html
  upload: index\.html

- url: .*
  script: natacalc.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
